<font color=blue><h1>Computation</h1>

<font color=blue><h3>What is a Computational Problem?</h3>

To start, a Computational Problem in Computer Science is a problem that can be solved by using an algorithm, more specifically, the problem can be viewed as a set of instances with possibly an empty set of solutions for every instance. The objective of Computational Problem's is to determine the amount of resources or computational complexity that is required to solve a problem and may even explain why it cannot be solved, at least for now with classic computers.
    
A common problem that is yet to be solved is matrix multiplication. The reason this is such an important problem is that matrix multiplication is used in many aspects of ourlives, even in ways we do not see. Examples of this is generating graphics in video games and recognising speech commands and with Video Games being the biggest industry for entertainment and most devices connected to the internet have some version of a voice assistant is proof of the importance of matrix multiplication.
    
So what exactly is the problem? It is how quickly can a computer solve the operation of multiplying a matrix. It is one of the simpilest forms of mathematics, taught at second level education in Ireland but in the digital world is where it gets more complex and to make matters that bit worse, the problem isn't that well understood and so, currently there isn't a known better way of solving the problem. Here is an example of a matrix.

In [1]:
#This is a package we would have seen in Topic Two
import numpy as np
#Creates Array A to use as a Matrix as Python doesn't
#have a built in type for Matricies
A = np.array([[1, 2, 3], [3, 4, 5]])
#Print out the contents of Array A
print(A)

[[1 2 3]
 [3 4 5]]


<font color=blue><h3>The Algorithms for multiplying Matricies</h3>

To start, by applying the definition of multiplying a matrix gives an algorithm that takes time on the order of n^3 field operations to multiply two n x n matricies over that field  (Θ(n3) in big O notation). First published in the end of the 1960's, 'Strassen's algorithm' (named after Volker Strassen) was introduced. This algorithm can solve Matrix multiplications faster than the standard matrix multiplication algorithm for larger matricies with a better asymptotic complexity (this is an indicator of performance and shows an algorithms limitations) but is slower by todays standards even though not many breakthroughs have happened. Until 2022, the next best algorithm for solving matricies was the 'matrix multiplication algorithm', designed by Josh Alman and Virginia Vassilevska Williams. The reason for this was the algorithms asymptotic complexity that runs in  O(n2.3728596) time but is considered a 'galactic algorithm' but we will get into that more later in the notebook.

In 2022, DeepMind an Artificial Intelligence subsidiary of a British company name Alphabet Inc. introduced AlphaTensor. Why this is worth talking about is because this is the biggest breakthrough in multiplying two matrices in about fifty years. How DeepMind went about making this breakthrough was by turning the problem into a single-player 3-D board game with the name 'TensorGame'. The board represents the multiplication problem itself and each move that the player makes in the game is the next step in solving the problem. Each move results in the algorithm. AlphaTensor learns what is the best step to make when multiplying matrices by using machine learning. 

In a quote from DeepMind's website, they said “AlphaTensor discovered algorithms that are more efficient than state-of-the-art for many matrix sizes. Our AI-designed algorithms outperform human-designed ones, which is a major step forward in the field of algorithmic discovery”. 

A notable acomplishment the AI has made is that it figured out how to multiply two 4 x 4 matrices with 47 multiplications rather than 64 by multiplying each row by each column seen in the matrix multiplication algorithm. Even futher, it takes two less steps tham Strassen's algorithm (49 steps) to complete which is why it is possibly the biggest breakthrough in around fifty years. 

<font color=blue><h3>A deeper look at Strassen's algorithm</h3>

Strassen's algorithm is seen as not optimal for practical applications for reasons such as for sparse matricies, better methods are available or submatricies in recursion take more space. Strassen's algorithm can be broken down into four steps with a python implementation of the algorithm. 
<ol>
    <li>First you must divide matrix A and Matrix B into four sub-matricies of size N/2 x N/2.</li>
    <li>Then multiply the seven matrices recursively.</li>
    <li>Compute submatricies of C.</li>
    <li>Finally, combine the submatricies into matrix C.</li>
</ol>

In [2]:
import numpy as np


def strassen_algorithm(x, y):
    if x.size == 1 or y.size == 1:
        return x * y

    n = x.shape[0]

    if n % 2 == 1:
        x = np.pad(x, (0, 1), mode='constant')
        y = np.pad(y, (0, 1), mode='constant')

    m = int(np.ceil(n / 2))
    a = x[: m, : m]
    b = x[: m, m:]
    c = x[m:, : m]
    d = x[m:, m:]
    e = y[: m, : m]
    f = y[: m, m:]
    g = y[m:, : m]
    h = y[m:, m:]
    p1 = strassen_algorithm(a, f - h)
    p2 = strassen_algorithm(a + b, h)
    p3 = strassen_algorithm(c + d, e)
    p4 = strassen_algorithm(d, g - e)
    p5 = strassen_algorithm(a + d, e + h)
    p6 = strassen_algorithm(b - d, g + h)
    p7 = strassen_algorithm(a - c, e + f)
    result = np.zeros((2 * m, 2 * m), dtype=np.int32)
    result[: m, : m] = p5 + p4 - p2 + p6
    result[: m, m:] = p1 + p2
    result[m:, : m] = p3 + p4
    result[m:, m:] = p1 + p5 - p3 - p7

    return result[: n, : n]

if __name__ == "__main__":

    x = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
    y = np.array([[-1, 0, 0], [0, -1, 0], [0, 0, -1]])
    print('Matrix multiplication result: ')
    print(strassen_algorithm(x, y))

Matrix multiplication result: 
[[-1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]


<b>And here is the look at the time complexity for Strassen's algorithm</b>
<ul>
    <li>Worst case time complexity: Θ(n^2.8074)</li>
    <li>Best case time complexity: Θ(1)</li>
    <li>Space complexity: Θ(logn)</li>
</ul>

<font color=blue><h3>A deeper look at Matrix Multiplication Algorithm</h3>

There isn't much to discuss about the Matrix Multiplication Algorithm as its pretty much the algorithm taught to students in maths class but there is a way to implement in Python as seen below, although a condition does have to be met, and this is if two matricies named A and B, and their dimensions are (M x N) and (P x Q) respectively, then the result of matrix C is (M x Q). Interestingly enough, in Python there are two ways to multiply two matricies. The first is using nested loops and other is using nested lists. I have included examples for both down below. Also felt it was worth mentioning that I have kept the valued for all of the 3x3 matricies to more so highlight the functionality rather than the results.

One thing I do want to mention about this algorithm. In the paragraph above, it was mentioned that it is considered a galactic algorithm. What this means is that the algorithm does outperform any other algorithm for problems that are considered large, but the problem is considered so large, it's never actually used for any data sets.

<b>Matrix Multiplication Algorithm in Python using nested loop's</b>

In [3]:
# Program to multiply two matrices using nested loops

# 3x3 matrix
X = [[4,7,16],
    [7,2,1],
    [11 ,10,9]]
# 3x3 matrix
Y = [[5,3,10],
    [6,12,5],
    [4,5,10]]
# result is 3x3
result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

# iterate through rows of X
for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]

for r in result:
   print(r)

[126, 176, 235]
[51, 50, 90]
[151, 198, 250]


In [4]:
# Program to multiply two matrices using list comprehension

# 3x3 matrix
X = [[4,7,16],
    [7,2,1],
    [11 ,10,9]]

# 3x3 matrix
Y = [[5,3,10],
    [6,12,5],
    [4,5,10]]

# result is 3x3
result = [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*Y)] for X_row in X]

for r in result:
   print(r)

[126, 176, 235]
[51, 50, 90]
[151, 198, 250]
